var constants = {
	ACTIVE_DATA_CHANGED: 'active_data_changed',
	ADD_PIECE_TO_CREATOR: 'add_piece_to_creator',
	ADD_SCALE_TO_SELECTED: 'add_scale_to_selected',
	CLEAR_GAMECREATOR_STORE: 'clear_gamecreator_store',
	CHANGE_FREEDRAW_STATE: 'change_freedraw_state',
	DELETE_SELECTED_PIECE_FROM_CREATOR: 'delete_selected_piece_from_creator',
	FETCHED_GAMECREATOR_LIST_FROM_SERVER: 'fetched_gamecreator_list_from_server',
	FREEDRAW_STATE_CHANGED: 'freedraw_state_changed',
	GAMECREATOR_STORE_CLEARED: 'gamecreator_store_cleared',
	GAMECREATOR_WAS_DELETED_ON_SERVER: 'gamecreator_was_deleted_on_server',
	ITERATE_SELECTED_PIECES_DEPTH: 'iterate_selected_pieces_depth',
	MOVE_SELECTED_PIECE: 'move_selected_piece',
	PENCIL_OPTIONS_CHANGED: 'pencil_options_changed',
	PIECE_WAS_SELECTED: 'piece_was_selected',
	PIECE_DELETED_FROM_CREATOR: 'piece_deleted_from_creator',
	PNG_ADDED_TO_GAME: 'png_added_to_game',
	REMOVE_PIECE_FROM_CREATOR: 'remove_pice_from_creator',
	ROTATE_CURRENT_SELECTED_PIECE: 'rotate_current_selected_piece',
	SAVE_GAMECREATOR_JSON: 'save_gamecreator_json',
	SAVE_GAMECREATOR_PNG: 'save_gamecreator_png',
	SET_SELECTED_INDEX: 'set_selected_index',
	SET_STATIC_PIECES: 'set_static_pieces',
	SET_CANVAS: 'set_canvas',
	SET_PENCIL_OPTIONS: 'set_pencil_options',
	SET_LOADED_DATA_TO_ID: 'set_loaded_data_to_id',
	SET_CREATOR_NAME: 'set_creator_name'
};

module.exports = constants;
